version: "3"
services:
  mysql8.0:
    image: mysql:8.0
    container_name: mysql-8.0
    ports:
      - 3380:3306
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=Jdh20010808
      - MYSQL_PWD=Jdh20010808
      - MYSQL_ROOT_PASSWORD=Jdh20010808
    volumes:
      - ./conf/my.cnf:/root/.my.cnf:ro
      - ./logs:/var/log/mysql:rw
      - ./mysql.sh:/etc/mysql.sh
