kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins
  namespace: kube-ops
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi                       #生产环境空间一定要设置比较大点
