apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: ns-saas
spec:
  ipFamilyPolicy: SingleStack
  ports:
  - name: redis-port
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
  sessionAffinity: None
  type: ClusterIP
